name: Build and Push Docker Image to GHCR

on:
  push:
    branches: [ "main" ]
    # --- Add paths filter ---
    # Only run workflow if changes occur in these paths/files
    paths:
      - 'app.py'
      - 'requirements.txt'
      - 'Dockerfile'
      - 'static/**'
      - 'templates/**'
      - '.github/workflows/docker-image.yml' # Re-run if workflow itself changes
    # --- End paths filter ---

  workflow_dispatch: # Allow manual trigger from GitHub UI

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    # Grant permissions for the GITHUB_TOKEN to write packages
    permissions:
      contents: read
      packages: write # Required to push to GHCR

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image to GHCR for multiple platforms
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
          # Use lowercase image name derived from repo name
          # tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name.toLowerCase() }}:latest